DISTRICT_ALIASES = {
    "blr south": "Bengaluru South",
    "blr north": "Bengaluru North",
    "blr east": "Bengaluru East",
    "blr west": "Bengaluru West",
    "bengaluru": "Bengaluru South",
    "bangalore": "Bengaluru South",
    "mysore": "Mysuru",
}

MOCK_CASES = [
    {
        "id": "KSP/BLR/2024/4521",
        "fir": "KSP/BLR/2024/4521",
        "crime_type": "Chain Snatching",
        "district": "Bengaluru South",
        "area": "Jayanagar 4th Block",
        "date": "15/03/2024",
        "status": "Investigating",
        "officer": "Inspector Sharma",
        "victims": 1,
        "accused": 2,
        "description": "Gold chain snatching reported near the metro exit during evening traffic. CCTV footage shows two suspects on a scooter.",
        "priority": "High",
        "pattern": "Evening commuter theft",
        "action": "Check nearby petrol bunks, review helmet-camera footage, and mark repeat route for surveillance.",
        "hotspot": True,
    },
    {
        "id": "KSP/BLR/2024/4522",
        "fir": "KSP/BLR/2024/4522",
        "crime_type": "Two-wheeler Theft",
        "district": "Bengaluru South",
        "area": "BTM Layout",
        "date": "18/03/2024",
        "status": "Open",
        "officer": "SI Ravi Kumar",
        "victims": 1,
        "accused": 3,
        "description": "A parked scooter was stolen from a residential street late at night. Suspected lock-picking gang activity.",
        "priority": "High",
        "pattern": "Parking lot theft",
        "action": "Match vehicle movement against toll and petrol pump records.",
        "hotspot": True,
    },
    {
        "id": "KSP/BLR/2024/4523",
        "fir": "KSP/BLR/2024/4523",
        "crime_type": "Robbery",
        "district": "Bengaluru East",
        "area": "Whitefield Main Road",
        "date": "22/03/2024",
        "status": "Chargesheeted",
        "officer": "Inspector Patil",
        "victims": 2,
        "accused": 4,
        "description": "Mobile phones and cash were robbed from two employees near a late-night bus stop. One accused identified from a prior case file.",
        "priority": "High",
        "pattern": "Late-night transit robbery",
        "action": "Link accused to previous transit-side robberies and verify station-side patrol logs.",
        "hotspot": True,
    },
    {
        "id": "KSP/BLR/2024/4524",
        "fir": "KSP/BLR/2024/4524",
        "crime_type": "Cybercrime",
        "district": "Bengaluru North",
        "area": "Hebbal",
        "date": "01/04/2024",
        "status": "Investigating",
        "officer": "SI Deepa Nair",
        "victims": 3,
        "accused": 1,
        "description": "A phishing campaign targeted senior citizens with fake courier messages and UPI links. Multiple small-value transfers reported.",
        "priority": "Medium",
        "pattern": "Phishing through messaging apps",
        "action": "Trace mule accounts and freeze beneficiary numbers linked to the payment trail.",
        "hotspot": False,
    },
    {
        "id": "KSP/MYS/2024/1182",
        "fir": "KSP/MYS/2024/1182",
        "crime_type": "Burglary",
        "district": "Mysuru",
        "area": "VV Mohalla",
        "date": "11/04/2024",
        "status": "Open",
        "officer": "Inspector Mohan",
        "victims": 1,
        "accused": 2,
        "description": "Night burglary at a jewelry shop with a rear shutter cut using industrial tools. CCTV camera power was disabled.",
        "priority": "High",
        "pattern": "Targeted shop burglary",
        "action": "Review hardware-store purchases of cutting tools and examine nearby lodges.",
        "hotspot": True,
    },
    {
        "id": "KSP/HDL/2024/0774",
        "fir": "KSP/HDL/2024/0774",
        "crime_type": "Fraud",
        "district": "Hubli",
        "area": "Dharwad Road",
        "date": "23/04/2024",
        "status": "Closed",
        "officer": "SI Ravi Kumar",
        "victims": 5,
        "accused": 1,
        "description": "Investment fraud using fake rental-property ads and advance deposit demands. The accused was traced through a bank account and phone IMEI.",
        "priority": "Medium",
        "pattern": "Advance-payment fraud",
        "action": "Cross-check bank mule networks and publish a local advisory for rental scams.",
        "hotspot": False,
    },
    {
        "id": "KSP/MNG/2024/2031",
        "fir": "KSP/MNG/2024/2031",
        "crime_type": "Assault",
        "district": "Mangalore",
        "area": "Kankanady",
        "date": "05/05/2024",
        "status": "Investigating",
        "officer": "Inspector Sharma",
        "victims": 2,
        "accused": 3,
        "description": "Street assault after a dispute near a late-night food stall. Witnesses mention a local group with prior nuisance complaints.",
        "priority": "Medium",
        "pattern": "Night-time public disorder",
        "action": "Collect witness statements from nearby shops and review prior beat-level complaints.",
        "hotspot": False,
    },
    {
        "id": "KSP/BLG/2024/6094",
        "fir": "KSP/BLG/2024/6094",
        "crime_type": "Vehicle Theft",
        "district": "Belagavi",
        "area": "Tilakwadi",
        "date": "12/05/2024",
        "status": "Open",
        "officer": "Inspector Patil",
        "victims": 1,
        "accused": 2,
        "description": "Motorbike theft from a commercial parking bay. Entry and exit timestamps suggest a coordinated two-person team.",
        "priority": "High",
        "pattern": "Commercial parking theft",
        "action": "Check nearby resale channels and CCTV from adjacent shops.",
        "hotspot": True,
    },
    {
        "id": "KSP/TMK/2024/8820",
        "fir": "KSP/TMK/2024/8820",
        "crime_type": "Kidnapping",
        "district": "Tumakuru",
        "area": "SS Puram",
        "date": "27/05/2024",
        "status": "Investigating",
        "officer": "SI Deepa Nair",
        "victims": 1,
        "accused": 3,
        "description": "Missing person complaint escalated into kidnapping suspicion after phone trace ended near the highway corridor.",
        "priority": "High",
        "pattern": "Highway interception",
        "action": "Start highway camera review and flag toll exits for the relevant time window.",
        "hotspot": False,
    },
    {
        "id": "KSP/DRW/2024/4410",
        "fir": "KSP/DRW/2024/4410",
        "crime_type": "Murder",
        "district": "Dharwad",
        "area": "Navanagar",
        "date": "08/06/2024",
        "status": "Chargesheeted",
        "officer": "Inspector Mohan",
        "victims": 1,
        "accused": 2,
        "description": "A homicide case linked to a property dispute. The scene analysis indicates a planned attack rather than a spontaneous altercation.",
        "priority": "High",
        "pattern": "Dispute-linked homicide",
        "action": "Preserve witness statements and keep property dispute records in the case file.",
        "hotspot": False,
    },
]

MOCK_CRIMINALS = [
    {"id": "C001", "name": "Rajesh Yadav", "alias": "Raja", "age": 34, "cases": 5, "area": "BTM Layout", "status": "Wanted", "crimes": ["Robbery", "Chain Snatching"]},
    {"id": "C002", "name": "Vikram Singh", "alias": "Vikki", "age": 41, "cases": 8, "area": "Jayanagar", "status": "Arrested", "crimes": ["Assault", "Murder"]},
    {"id": "C003", "name": "Suresh Kumar", "alias": "Suri", "age": 28, "cases": 3, "area": "Koramangala", "status": "Under Trial", "crimes": ["Theft", "Burglary"]},
    {"id": "C004", "name": "Deepak Nair", "alias": "Deep", "age": 38, "cases": 6, "area": "Hebbal", "status": "Wanted", "crimes": ["Vehicle Theft", "Robbery"]},
    {"id": "C005", "name": "Mohan Das", "alias": "Monu", "age": 25, "cases": 1, "area": "Electronic City", "status": "Released", "crimes": ["Fraud"]},
    {"id": "C006", "name": "Naveen Bhat", "alias": "NB", "age": 36, "cases": 4, "area": "Whitefield", "status": "Wanted", "crimes": ["Cybercrime", "Fraud"]},
]